### PR TITLE
Fix Go 1.15 support with new test certificates

### PR DESCRIPTION
**Pull request by ilammy**
This PR fixes a recently found issue with TLS tests failing after updating to Go 1.15.

### Backstory

We have decided to update Go versions used for testing and accidentally discovered a regression with Go 1.15. Integration tests with TLS started to fail with exceptions like

```
  File "/home/user/.local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 481, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/user/.local/lib/python3.5/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL SYSCALL error: EOF detected

(Background on this error at: http://sqlalche.me/e/e3q8)
```

The issue did not reproduce with Go 1.14 and it was weird.

Our initial assessment of the changelog has pointed [some updates in `crypto/tls`](https://golang.org/doc/go1.15#crypto/tls) which – spoiler alert! – turned out to be a red herring.

### What actually went wrong

Well, I've reproduced the issue in CircleCI environment but that did not help very much. So I just started AcraServer built with Go 1.15, configured AcraConnector, a database with TLS, etc., and... here's what I saw in AcraServer's logs when trying to access the database via AcraConnector:

```
CEF:0|cossacklabs|acra-server-ee|0.85.0|584|Can't initialize tls connection with db|6|client_id=keypair1 decrypt_mode=wholecell error=x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG\=x509ignoreCN\=0 proxy=server unixTime=1600779074.282 
CEF:0|cossacklabs|acra-server-ee|0.85.0|584|Can't process SSL request|6|client_id=keypair1 decrypt_mode=wholecell error=x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG\=x509ignoreCN\=0 proxy=server unixTime=1600779074.283 
```

Quick testing has shown that setting `GODEBUG=x509ignoreCN=0` makes the issue go away, even for integration tests. Another quick look has shown that the certificates we use indeed do not contain Subject Alternate Names (SAN).

Another look at the patch notes revealed that [Go 1.15 drops legacy support for CommonName as host name][1] if there
are no Subject Alternate Names in the certificates.

[1]: https://golang.org/doc/go1.15#commonname

### How to fix this issue

Instead of putting `localhost` into Common Name, add a Subject Alternate Name with that host name, and use something which does not look like a hostname in Common Name.

Here is how the old certificates look:

<details>
<summary>Old CA certificate</summary>

```
$ openssl x509 -text -noout -in tests/ssl/ca/ca.crt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            3c:4b:87:bf:7b:a7:ef:16:25:7f:70:84:a1:e6:bd:d2:8d:8e:f8:73
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = GB, ST = London, L = London, O = Global Security, OU = IT, CN = ca-localhost
        Validity
            Not Before: Jan 31 12:48:33 2019 GMT
            Not After : Jan 18 12:48:33 2069 GMT
        Subject: C = GB, ST = London, L = London, O = Global Security, OU = IT, CN = ca-localhost
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:ee:97:df:c7:c4:52:e2:79:55:41:c9:b4:8c:e7:
                    bc:34:9f:7f:05:74:67:b6:ea:46:45:17:ba:36:6e:
                    e2:63:b6:65:5b:be:44:60:31:7a:7c:f1:02:96:a0:
                    c9:52:11:1d:c2:36:3b:95:06:8f:18:a4:f0:94:a3:
                    c2:b8:4f:63:c6:f8:f3:c6:2f:c5:7f:ee:dc:0c:24:
                    d7:15:1c:f7:4e:ca:b0:79:96:b6:25:c3:0b:76:1d:
                    d1:ba:9d:a7:df:61:0b:4b:48:f0:4b:b8:4e:45:75:
                    f3:53:d5:f9:23:86:73:9f:b6:a6:6e:22:d6:83:e5:
                    3d:07:b6:8e:9e:f0:77:ef:13:60:e2:4b:6e:c3:2e:
                    6f:15:d9:6c:b6:01:e7:a7:99:e7:f6:2c:a4:e5:68:
                    a2:94:1f:5f:be:18:0d:cb:9c:a8:bb:66:71:e8:45:
                    14:e0:14:bc:87:21:f5:e4:f1:5a:5c:0d:4e:1d:25:
                    3a:02:c5:ff:25:df:b9:21:e6:f9:4b:70:5d:22:ee:
                    81:54:e0:9a:56:19:ae:9e:fd:45:7b:bd:1c:da:a8:
                    fc:97:c8:a5:53:0a:07:f4:74:98:a8:02:ec:ab:5d:
                    5f:f4:ec:5e:5b:1a:08:57:45:de:96:01:63:6d:61:
                    f5:fd:c4:bb:1f:d5:8a:5a:9f:29:8e:2e:4c:fe:e9:
                    fe:ff
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                21:74:60:D6:C2:B2:2C:B4:06:D8:05:10:C2:03:7A:A8:35:BC:36:FC
            X509v3 Authority Key Identifier: 
                keyid:21:74:60:D6:C2:B2:2C:B4:06:D8:05:10:C2:03:7A:A8:35:BC:36:FC

            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: sha256WithRSAEncryption
         d2:ae:2a:58:b9:18:05:19:07:94:b9:1c:16:1c:d3:cc:99:27:
         80:c0:27:7b:f6:12:3d:cb:0d:0c:fb:da:30:8c:0d:82:c0:d8:
         b2:1f:b2:0e:74:fb:86:08:32:98:32:ac:ed:09:bc:ba:83:9c:
         75:a4:81:83:a5:34:76:4d:80:4c:e8:39:05:47:87:ed:76:a2:
         53:fa:9d:ce:11:91:54:20:50:6e:da:90:35:5f:79:0a:0c:6a:
         bd:c3:43:6e:86:8c:85:d0:09:31:39:7e:66:e6:89:fd:7f:12:
         b7:60:a2:41:20:06:96:2e:b2:e9:8d:ef:e1:55:bf:ba:61:80:
         27:a0:62:f2:3a:16:78:21:89:a0:cf:24:a3:e4:a6:5d:d8:5a:
         2b:9a:31:bc:3a:ed:5c:07:85:0c:8b:c0:88:b9:d6:ee:43:49:
         bb:86:8e:9e:32:c0:c3:ed:80:09:68:e6:e6:35:8e:10:e9:68:
         da:69:bc:c0:a6:8d:e2:ab:fb:26:5e:91:f0:d9:f5:4f:82:24:
         d9:c3:df:51:61:d6:40:3e:fb:c9:4f:5d:d0:8e:07:22:78:93:
         a9:f6:ac:aa:5d:18:f8:e7:fb:88:2d:0d:47:42:9e:dd:87:97:
         dd:71:c8:5c:5c:26:bd:cc:f7:51:6d:3f:94:88:c7:92:c0:6f:
         59:8a:a8:25
```

</details>

<details>
<summary>Old client certificate</summary>

```
$ openssl x509 -text -noout -in tests/ssl/acra-writer/acra-writer.crt 
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            04:90:aa:e8:b4:38:54:1e:16:3b:7a:9a:c1:70:fb:83:78:f5:cd:0e
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = GB, ST = London, L = London, O = Global Security, OU = IT, CN = ca-localhost
        Validity
            Not Before: Jan 31 12:48:34 2019 GMT
            Not After : Jan 18 12:48:34 2069 GMT
        Subject: C = GB, ST = London, L = London, O = Global Security, OU = IT, CN = localhost
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:db:c7:c4:cc:eb:fb:e4:27:9f:ca:63:0f:82:1c:
                    26:5b:f2:43:35:e3:5a:be:3f:a4:56:5e:91:48:03:
                    ce:0b:7e:cf:c2:de:ba:f2:ca:25:42:42:71:ca:7b:
                    49:7d:91:04:ff:a3:49:2c:bb:28:aa:61:b5:62:ed:
                    e2:7a:5f:d8:ae:e2:7a:68:66:2c:74:99:95:49:5d:
                    6c:b2:ba:81:0f:0a:ea:a3:e9:97:14:ae:41:98:14:
                    da:19:d3:af:c0:5d:59:dc:9d:9f:2c:7b:52:3e:ef:
                    95:ea:c5:5d:1d:60:54:40:2c:a9:fb:40:5b:17:e2:
                    2e:af:88:75:88:a4:be:65:cc:72:15:2b:0f:b8:ab:
                    81:78:f9:52:ec:9a:d4:9a:ac:12:2c:3a:b3:cd:5d:
                    8f:bc:55:73:63:71:01:f0:f2:b7:f5:83:e3:01:90:
                    c0:d7:10:6a:39:47:89:86:9c:09:79:ab:db:bf:04:
                    d9:eb:ed:da:6f:54:70:86:9e:9b:e2:a0:df:8a:a1:
                    fb:21:7c:3e:bb:52:f6:77:2e:b4:55:21:e3:52:1d:
                    ce:26:7e:2d:32:58:07:6b:71:0b:59:ca:08:30:66:
                    e0:f9:97:79:e6:81:13:07:ed:b2:ff:eb:08:a6:0a:
                    fb:a7:0b:84:09:cf:6e:48:ec:0f:e1:76:72:23:46:
                    6a:33
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha256WithRSAEncryption
         11:97:17:70:34:b0:93:99:f5:c7:2d:f4:8a:61:15:8c:db:b6:
         9a:45:22:f4:e4:a6:09:7d:45:10:99:52:be:a9:f7:9b:94:e6:
         f5:5a:97:63:61:4d:76:48:d6:61:87:e8:dc:9b:b4:e1:ab:68:
         b2:5d:ac:5c:7d:70:40:9b:07:7a:f8:0f:21:5f:7a:9d:94:b2:
         ae:6d:a9:dd:c6:a1:5c:d2:17:c2:70:38:a4:9b:62:a4:66:73:
         3b:ed:46:c7:8b:a4:bd:2c:b9:f8:02:81:4f:f7:34:8c:6a:41:
         31:7d:2e:5a:36:79:17:75:d7:a2:e4:53:a3:58:81:6a:82:e9:
         17:44:d5:e2:85:3c:59:b9:77:21:7d:2c:96:74:7f:2b:de:e9:
         f4:30:a0:d0:59:49:0c:32:47:8b:fe:34:29:5f:fa:0c:bc:67:
         32:89:4e:7d:77:e8:67:e1:af:64:b9:2b:c5:ed:74:5e:99:2f:
         e1:37:b9:75:c4:d2:30:52:d9:16:af:3f:29:6b:b4:12:a0:a9:
         97:03:75:9f:d1:a1:f9:0f:e3:07:5d:8a:75:dd:52:19:6a:ce:
         29:2f:14:fb:30:51:46:2e:8d:10:22:f3:d1:c7:9f:96:18:66:
         58:a4:11:de:c8:31:f1:17:e5:47:d6:a7:78:5c:6b:bf:fb:0b:
         cf:9b:be:ab
```

</details>

And here are the new ones:

<details>
<summary>New CA certificate</summary>

```
$ openssl x509 -text -noout -in tests/ssl/ca/ca.crt 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            43:6e:0c:5b:e4:aa:df:a0:1f:01:4c:ba:46:ad:61:45:81:c8:ec:28
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = GB, ST = London, L = London, O = Global Security, OU = IT, CN = Test CA certificate
        Validity
            Not Before: Sep 22 16:05:34 2020 GMT
            Not After : Sep 10 16:05:34 2070 GMT
        Subject: C = GB, ST = London, L = London, O = Global Security, OU = IT, CN = Test CA certificate
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:be:12:60:a8:38:dc:80:be:30:2f:5b:0a:b1:55:
                    36:94:0a:43:c3:03:3a:36:7f:ae:f1:83:e8:69:a4:
                    e2:73:26:e0:4e:5d:e7:79:cc:1b:df:4a:d1:88:4c:
                    85:af:0b:34:ad:ad:22:ba:3d:22:c4:e8:9e:99:33:
                    51:4d:8e:99:49:68:3f:ee:44:e4:51:58:0f:37:48:
                    0a:aa:3a:cc:e3:c8:3c:fe:41:db:3b:a7:fc:ec:a8:
                    4b:bd:99:a0:56:3b:73:0a:d0:52:e5:f5:c1:0d:87:
                    87:07:f9:78:4c:fe:ab:3c:09:7b:06:a4:3c:fa:1c:
                    c0:d4:83:27:5b:44:27:64:76:55:01:b3:e9:30:2b:
                    86:a6:8e:12:9e:de:65:9b:25:22:9d:89:da:98:03:
                    f3:47:cd:84:ee:58:84:98:c9:d2:a2:e3:31:a9:47:
                    1b:a8:dc:08:eb:73:f3:ae:ce:d4:78:66:ba:19:8e:
                    91:4e:40:82:e7:63:6a:bd:17:05:56:45:1f:b7:96:
                    c6:7c:10:95:46:07:64:d3:08:c9:ce:56:70:74:dc:
                    77:46:56:c4:29:c6:0a:27:dd:f3:1e:43:27:7a:bc:
                    36:87:9c:8c:38:f1:75:21:04:f6:95:a1:ab:2b:ee:
                    25:48:9d:1f:71:91:9a:bf:1e:5a:17:48:7a:99:86:
                    98:0b
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Subject Alternative Name: 
                DNS:localhost
            X509v3 Subject Key Identifier: 
                E9:58:50:C8:E6:25:61:E2:D6:B2:51:5B:21:BD:49:BB:83:A0:4A:A8
            X509v3 Authority Key Identifier: 
                keyid:E9:58:50:C8:E6:25:61:E2:D6:B2:51:5B:21:BD:49:BB:83:A0:4A:A8

    Signature Algorithm: sha256WithRSAEncryption
         06:a8:86:5b:a3:c0:e0:c1:04:08:59:8a:bb:cd:98:ac:04:2b:
         54:dd:b4:eb:de:a9:9c:86:c9:3d:32:cd:a0:b7:5a:82:3e:2d:
         5c:17:11:5c:ef:3b:83:d7:a7:7e:e2:5f:5c:02:f6:e8:52:47:
         bd:f9:f0:cc:32:24:1e:42:22:d7:4a:01:25:92:e3:43:fe:81:
         43:04:7e:8c:34:84:5d:e4:5f:0d:a8:c0:e8:b8:4e:e6:20:d1:
         a7:d0:bf:0e:f7:f3:72:7a:56:eb:22:0e:13:eb:a0:76:ba:e8:
         08:71:a4:e6:4e:5a:6e:3c:06:21:2b:a8:6c:98:13:73:30:df:
         fa:a5:a9:00:61:29:d4:9a:15:3e:de:10:68:22:a7:17:03:5b:
         5c:96:b7:ed:77:f2:41:a8:cf:ec:45:59:95:41:ca:af:81:56:
         71:a3:5d:d9:98:73:4d:53:2d:42:53:33:bf:90:ea:73:b0:81:
         4f:b6:b5:f9:a2:ed:b8:71:17:d4:17:59:44:17:4d:7f:d3:b0:
         bf:b0:ef:6e:22:4e:dd:d3:2a:db:db:6b:f9:11:b2:8f:c8:c5:
         2e:f8:bb:09:45:bd:bf:0f:d2:d6:b6:0e:b0:6f:ad:81:d4:1c:
         e9:6a:73:8f:79:2e:a5:17:5f:c0:35:93:db:93:58:33:25:9d:
         57:9c:10:e8
```

</details>

<details>
<summary>New client certificate</summary>

```
$ openssl x509 -text -noout -in tests/ssl/acra-writer/acra-writer.crt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            3b:84:c1:a2:8a:44:d9:5f:99:ac:0b:d1:ef:19:af:36:6b:cb:b3:51
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = GB, ST = London, L = London, O = Global Security, OU = IT, CN = Test CA certificate
        Validity
            Not Before: Sep 22 16:05:34 2020 GMT
            Not After : Sep 10 16:05:34 2070 GMT
        Subject: C = GB, ST = London, L = London, O = Global Security, OU = IT, CN = Test leaf certificate
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:de:fa:c7:73:11:6f:6d:3f:67:13:dc:b7:b7:71:
                    ae:28:7b:b3:0c:0e:3a:6a:97:9c:31:87:25:0b:fc:
                    6f:85:45:74:d9:4b:0f:a1:4e:85:b9:3e:94:e5:9f:
                    60:46:39:56:cc:aa:59:b3:f5:e6:51:80:c5:d5:a5:
                    6b:d3:77:f1:67:15:6b:3e:3f:db:41:0e:ba:62:ca:
                    d3:26:9a:50:05:de:9f:a8:45:6c:61:14:d6:87:33:
                    e1:d1:21:9e:61:4c:85:c7:c1:72:50:80:e2:42:70:
                    98:08:e9:19:22:40:bf:11:09:3b:61:ee:7b:52:3a:
                    60:8a:f5:0f:65:87:8d:ec:b4:ef:c4:05:64:25:4e:
                    8b:33:0a:86:6a:f7:41:f1:60:6b:0d:f1:15:98:90:
                    40:d7:10:21:db:3a:b5:cf:70:94:99:7c:bb:37:fa:
                    de:e2:f2:30:f2:82:f2:2a:fe:f0:ab:e5:56:f1:14:
                    99:92:5a:5c:f9:86:e1:cc:39:d2:b4:0f:bc:2d:47:
                    a6:2d:f4:77:52:fa:3e:43:49:96:fa:5a:56:e9:c9:
                    32:78:c8:d3:af:c6:7a:ed:cf:35:a6:26:c7:0f:1f:
                    d8:db:96:b8:5a:23:2a:cc:fe:93:ec:17:46:e2:11:
                    fe:12:81:ab:26:07:2d:fc:77:4d:8d:fb:9b:0c:76:
                    92:23
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Subject Alternative Name: 
                DNS:localhost
    Signature Algorithm: sha256WithRSAEncryption
         a3:78:b0:f4:39:b4:b4:f9:67:69:70:25:55:60:5f:3b:93:97:
         22:67:82:c1:52:a7:56:29:05:d1:d4:fd:44:56:c5:79:7b:8a:
         b2:7b:5d:9f:1c:92:5f:a8:a0:cc:19:a6:4b:66:23:8d:a7:53:
         57:f6:7e:68:95:d0:78:8c:f6:1f:36:aa:ba:3d:74:c8:74:be:
         e4:28:39:0c:9c:27:da:bd:c0:a7:2c:7b:2d:1b:ab:a7:07:6a:
         e2:16:c7:c9:87:da:38:42:95:33:09:ea:f6:e5:a3:1f:00:de:
         40:bc:de:1a:b6:c6:ea:eb:31:e5:68:a8:e6:53:91:12:a7:0c:
         0a:05:72:06:be:8b:5e:f0:ca:fe:e3:54:ba:ba:cf:a0:43:f7:
         ab:02:3c:65:95:e4:c4:9a:b7:ad:d2:ad:0c:d5:14:0f:1e:24:
         d1:ff:e6:ee:c4:ac:ea:3f:a0:da:f1:fc:5f:59:43:88:8c:d3:
         84:d4:07:a6:3e:07:b6:5b:76:11:47:d2:82:b7:67:35:e1:d8:
         32:df:00:35:56:c5:5f:1b:ae:e0:c1:a0:5c:40:94:19:93:19:
         c6:24:11:df:23:38:cd:32:4a:cb:3d:27:29:0d:6f:d0:4d:4f:
         b4:79:aa:da:cd:c7:87:15:ad:99:30:12:a1:48:46:dd:2a:b5:
         26:bc:54:18
```

</details>

The interface for setting these extension variables is not a paragon of usability, but OpenSSL is what it is. We need to provide a configuration file and pass the section names to use. Since those are test certificates, we can use only bare minimum of fields. It took a while to figure out the correct settings.

Test certificates and private key files are updated and committed into the repository. This will trigger recently added GitHub alert about that. You can disregard it.

### Updated Docker images

The database images we use contain the certificates and keys generated here, in Acra CE. Switch to updated versions of the images which contain the freshly generated data.

| Database | Old tag | New tag |
| -- | -- | -- |
| PostgreSQL | `cossacklabs/postgresql-ssl:11` | `cossacklabs/postgresql-ssl:11-1` | 
| MySQL | `cossacklabs/mysql-ssl:5.7.25` | `cossacklabs/mysql-ssl:5.7.25-1` |
| MariaDB | `cossacklabs/mariadb-ssl:10.3` |  `cossacklabs/mariadb-ssl:10.3-1` |

Since the images are tied to contents of `tests/ssl`, new tags are introduced and used. After all branches of CE and EE have migrated to the new certificate files it will be possible to update the base tags. (Or, most likely, we'll leave them as it).

The images have been manually built and uploaded to Docker Hub by me. The Dockerfiles can be found in `tests/docker`.

### Updated Go versions

Finally, update the Go versions that we use:

- 1.15 – latest stable version
- 1.14 – the previous one
- 1.13 – the oldest version we support

(*Right now* the oldest version is 1.11, but #414 bumps that to 1.13 so I'm using it to avoid conflicts.)

### CODE REVIEW

**Comment by storojs72** [comment]
Nice work, @ilammy. You even worried about merge conflicts with https://github.com/cossacklabs/acra/pull/414. Thank you

**Review by storojs72 — APPROVED** [review]

**Review by shadinua — APPROVED** [review]

**Comment by iamnotacake** [comment]
> One question - do we need setting GOROOT and GO111MODULE variables for Go versions higher than 1.11?

Not sure about `GO111MODULE`, but we need `GOROOT`, at least one script (`.circleci/check_gotest.sh`) relies on it.

**Comment by Lagovas** [comment]
`GODEBUG=x509ignoreCN=0` does it turn off checks at runtime or should be passed at compile time? Just to know what to do if someone will use old certificates in own infra and will use new containers) Is it will help them or not)

**Review by Lagovas — APPROVED** [review]

**Comment by ilammy** [comment]
@storojs72,

> You even worried about merge conflicts with #414.

I just realized that changing the GOROOT values might cause conflicts after all. Well, I'll fix that in your PR if this one is going to be merged earlier.

> do we need setting GOROOT

It seems that only `.circleci/check_configs.sh` is currently relying on it being set directly. Other scripts set it based on VERSION. I guess `check_configs.sh` can be taught to use VERSION value as well (say, pick the latest version).

However, right now I'd say that we should keep it in the **general_validation** step. Everywhere else it's not needed, it seems.

> and GO111MODULE variables for Go versions higher than 1.11?

Since Acra has `go.mod` file, we don't really need to set GO111MODULE anymore. It's default value will work in our case.

**Comment by ilammy** [comment]
@Lagovas,

> GODEBUG=x509ignoreCN=0 does it turn off checks at runtime or should be passed at compile time?

It's a runtime switch. If anyone uses borked certificates then they can set it for `acra-server` as a workaround.

**Review by vixentael — APPROVED** [review]

**Pull request merged**
